apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app-dev
  template:
    metadata:
      labels:
        app: node-app-dev
    spec:
      containers:
        - name: node-app
          image: bkk/node-app-dev:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service-dev
spec:
  type: NodePort
  selector:
    app: node-app-dev
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30008
