
services:
  app:
    build: .
    container_name: node_app_dev
    restart: always
    env_file:
      - ./envs/.env.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
      - rabbitmq

  postgres:
    image: postgres:latest
    container_name: postgres_dev
    restart: always
    env_file:
      - ./envs/.env.dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_dev
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_dev
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:
