name: CI/CD Deployment

on:
  push:
    branches:
      - develop
     # - staging

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Development
        if: github.ref == 'refs/heads/develop'
        run: ansible-playbook ansible/dev_deploy_playbook.yml -i ansible/inventory/hosts.yml

      # - name: Deploy to Staging
      #   if: github.ref == 'refs/heads/staging'
      #   run: ansible-playbook ansible/stg_deploy_playbook.yml -i ansible/inventory/hosts.yml
